language: python
cache: pip
addons:
  apt:
    packages:
      - librtmidi-dev
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install:
  - pip install -e '.[test]'
script: pytest
