language: python
cache: pip
addons:
  apt:
    packages:
      - librtmidi-dev
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # 3.10 nightly build
               # enabled now
               # to troubleshoot https://github.com/SpotlightKid/python-rtmidi/issues/68
install:
  - >
    if [ "$TRAVIS_PYTHON_VERSION" == "nightly" ]; then
      pip install Cython ;
      pip download python-rtmidi ;
      tar xvf python-rtmidi-*.tar.gz ;
      rm python-rtmidi-*.tar.gz ;
      cd python-rtmidi-* ;
      make clean-build ;
      python setup.py install ;
      cd .. ;
    fi
  - pip install -e '.[test]'
script: pytest
